# Generated by Django 3.1 on 2020-12-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=15)),
                ('operacion', models.CharField(max_length=15)),
                ('superficie', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('banno', models.IntegerField()),
                ('ubicacion', models.TextField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
