# Generated by Django 3.1 on 2020-12-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_propiedad_imgane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_galeria', models.FileField(null=True, upload_to='Propiedades')),
                ('propiedad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.propiedad')),
            ],
        ),
    ]
